### ISSUE TITLE
Object #<Object> has no method 'grade' from example code

### ISSUE THREAD

**Issue by manchuwook** [sebs/node-fuzzylogic#5]
Seems to not use module.exports standard for nodejs.
```
    var probabNoAttack          = fuzzylogic.triangle(threat, 0, 20, 40);
                                             ^
TypeError: Object #<Object> has no method 'triangle'
    at threatCalc (c:\dev\brain\livingmachine.js:185:46)
    at Object.<anonymous> (c:\dev\brain\livingmachine.js:194:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

```

**Comment by sebs** [comment]
fixed in latest ... sorry
